/// Flutter icons CourseiIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CourseiIcons
///      fonts:
///       - asset: fonts/CourseiIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CourseiIcons {
  CourseiIcons._();

  static const _kFontFam = 'CourseiIcons';

  static const IconData ic_playlist = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData ic_rate = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData ic_start_course = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData ic_currency = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData ic_link = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData ic_menu_vertical = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData ic_people = const IconData(0xe806, fontFamily: _kFontFam);
}
